onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
