onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  ajv@<6.14.0: '>=6.14.0'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  minimatch@<10.2.1: '>=10.2.1'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
