allowBuilds:
  '@clerk/shared': true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - minimatch@10.2.3
  - flatted@3.4.0
  - next@16.1.7
  - flatted@3.4.2
  - brace-expansion@5.0.5
  - picomatch@2.3.2
  - picomatch@4.0.4
  - next@16.2.3
  - postcss@8.5.10
  - '@clerk/shared@3.47.4'
  - '@clerk/nextjs@6.39.2'
  - fast-uri@3.1.1
  - fast-uri@3.1.2
  - next@16.2.5
  - '@clerk/clerk-react@5.61.6'
  - '@clerk/nextjs@6.39.3'
  - '@clerk/backend@2.33.3'
  - '@clerk/shared@3.47.5'
  - next@16.2.6
  - brace-expansion@5.0.6
  - js-cookie@3.0.6
  - markdown-it@14.1.2
  - linkify-it@5.0.1
  - '@babel/core@7.29.1'
  - brace-expansion@5.0.7
  - linkify-it@5.0.2
  - sharp@0.35.0
  - next@16.2.11
  - postcss@8.5.12
  - brace-expansion@5.0.8
  - postcss@8.5.23
  - brace-expansion@5.0.9
  - nanoid@3.3.16
  - nanoid@3.3.18
  - postcss@8.5.18

onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  ajv@<6.14.0: '>=6.14.0'
  js-cookie@<=3.0.5: ^3.0.6
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
  minimatch@<10.2.1: '>=10.2.1'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
